# Generated by Django 4.0.4 on 2022-05-26 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnalyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('win_w', models.IntegerField()),
                ('draw_w', models.IntegerField()),
                ('lose_w', models.IntegerField()),
                ('win_b', models.IntegerField()),
                ('draw_b', models.IntegerField()),
                ('lose_b', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('black', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('result', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco_ww', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('eco_dw', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('eco_lw', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('eco_b', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('eco_db', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('eco_lb', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('n_eco_ww', models.IntegerField()),
                ('n_eco_dw', models.IntegerField()),
                ('n_eco_lw', models.IntegerField()),
                ('n_eco_b', models.IntegerField()),
                ('n_eco_db', models.IntegerField()),
                ('n_eco_lb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('title', models.CharField(blank=True, choices=[('CM', 'Candidato Maestro'), ('MF', 'Maestro Fide'), ('MI', 'Maestro Internacional'), ('GM', 'Gran Maestro')], max_length=2)),
                ('url', models.CharField(blank=True, default=None, max_length=100)),
                ('country', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('city', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('biography', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('firstName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('lastName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rated', models.IntegerField(blank=True, null=True)),
                ('n_draw', models.IntegerField(blank=True, null=True)),
                ('n_loss', models.IntegerField(blank=True, null=True)),
                ('n_win', models.IntegerField(blank=True, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nick', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('site', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('date', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('white', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('elo_w', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('elo_b', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('black', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('result', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('variant', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('eco', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('opening', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('scienc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scienc', to='plataforma.dataanalyst')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_game', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('move_game', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header', to='plataforma.header')),
                ('id_partidas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='plataforma.perfil')),
                ('moves', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='plataforma.moves')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ImageField(upload_to='../imagenes/Profiles/')),
                ('picture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='plataforma.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Elo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('games', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('rd', models.IntegerField()),
                ('prog', models.IntegerField()),
                ('ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='plataforma.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='dataanalyst',
            name='opening',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening', to='plataforma.opening'),
        ),
    ]
