# Generated by Django 4.0.3 on 2022-04-15 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('titulo', models.CharField(blank=True, choices=[('CM', 'Candidato Maestro'), ('MF', 'Maestro Fide'), ('MI', 'Maestro Internacional'), ('GM', 'Gran Maestro')], max_length=2)),
                ('url', models.CharField(blank=True, default=None, max_length=100)),
                ('country', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('bio', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('firstName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('lastName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('rating', models.IntegerField(blank=True)),
                ('rated', models.IntegerField(blank=True)),
                ('n_draw', models.IntegerField(blank=True)),
                ('n_loss', models.IntegerField(blank=True)),
                ('n_win', models.IntegerField(blank=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ImageField(upload_to='../imagenes/Profiles/')),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Elo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('games', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('rd', models.IntegerField()),
                ('prog', models.IntegerField()),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='plataforma.perfil')),
            ],
        ),
    ]
