# Generated by Django 4.0.4 on 2022-05-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='id_partidas',
            new_name='id_perfil',
        ),
    ]
