# Generated by Django 4.0.4 on 2022-07-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='kind',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
