# Generated by Django 4.0.3 on 2022-04-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
