# Generated by Django 4.0.4 on 2022-05-26 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_rename_id_partidas_games_id_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='scienc',
        ),
        migrations.AddField(
            model_name='dataanalyst',
            name='header',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Header', to='plataforma.header'),
        ),
    ]
