# Generated by Django 4.0.3 on 2022-04-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_perfil_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='n_draw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='n_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='n_win',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rated',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
