# Generated by Django 4.0.4 on 2022-05-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_remove_header_scienc_dataanalyst_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataanalyst',
            name='header',
        ),
        migrations.AddField(
            model_name='header',
            name='scienc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='plataforma.dataanalyst'),
        ),
    ]
