# Generated by Django 4.0.4 on 2022-05-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_remove_dataanalyst_header_header_scienc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='opening',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
