# Generated by Django 4.0.4 on 2022-05-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_alter_header_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moves',
            name='black',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moves',
            name='white',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
