# Generated by Django 4.0.4 on 2022-08-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_opening_name_eco_b_opening_name_eco_db_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='black',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='event',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='site',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='variant',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='white',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
