# Generated by Django 4.0.4 on 2022-05-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_alter_moves_black_alter_moves_white'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='header_game',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='move_game',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
